### ISSUE TITLE
SSL certificate verify failed on fresh CentOS 7 VM

### ISSUE THREAD

**Issue by paddyroddy** [ome/ansible-role-postgresql-client#4]
I'm running the examples in https://github.com/ome/omero-deployment-examples namely the [one-node example](https://github.com/ome/ansible-example-omero-onenode)

An issue I'm encountering is in this step
![image](https://user-images.githubusercontent.com/15052188/145065037-7bd1efd2-d606-46be-a4b1-878a5455df8f.png)

I can fix this manually by `ssh`ing into the VM and running the following
```
sudo yum install -y ca-certificates
sudo update-ca-trust force-enable
```

However, if I try to do these in an `ansible` role the `ca-certificates` works, but the second command is clearly not being run as expected. Is there something I can do to fix this, or does this role need modifying? I'm new to all of this

**Comment by joshmoore** [comment]
Hi @paddyroddy. If this is your own VM, then updating the ca-certificates package sounds like the correct strategy. In other words, the URLs are correct (as far as we know) but as those (or other) servers update their certificates, operating systems that try to access them will need to update their knowledge of trusted certificates.

That's not something that an individual role like this one should be responsible for, but one could imagine a dedicated role or playbook making sure that the certificates are up-to-date.

**Comment by paddyroddy** [comment]
Okay, thanks. Yes, I'm running this on my own VM.

So I've made an `ansible` role in which the following two commands are run:
```
- name: Install the ca-certificates package
  become: true
  yum:
    name: "ca-certificates"
    state: installed

- name: Enable the dynamic CA configuration feature
  become: true
  command: "update-ca-trust force-enable"
```
I can see that the first step is installed, but the second doesn't appear to work. Do you have any idea what might be causing this?

**Comment by joshmoore** [comment]
What error are you seeing? Or is it just silently doing nothing?

**Comment by paddyroddy** [comment]
That step doesn't error. But then the one above gets hit, which means it's clearly not doing what I think it is

**Comment by joshmoore** [comment]
I may just need more ☕ but I'm not following. Can you show me the output?

**Comment by paddyroddy** [comment]
Apologies, I had to create a new VM to fully recreate this. So basically we've taken i.e. the one node demo from that repo above and we've added a custom role (in addition to the 3 `ome` roles) which basically makes sure that the certificates are up-to-date - as well as doing some `python` stuff.

So you can see that `ca-certificates` is installed, and that reports `changed` for the second step.

![image](https://user-images.githubusercontent.com/15052188/145202755-7c1dd1d4-c1c2-47be-9bb7-1ccb5b0dfeb5.png)

**Comment by sbesson** [comment]
@paddyroddy from your example, I wonder if the issue is not that the VM has an outdated version of `ca-certificates`. I am inferring this from thefact that the  ca-certificates installation task reports ok rather than changed.

What happened if you do

```
- name: Install the ca-certificates package
  become: true
  yum:
    name: "ca-certificates"
    state: latest
```
?
